apiVersion: v1
kind: Service
metadata:
  name: se-kafka
spec:
  selector:
    app: se-kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: kafka-host
      port: 29092
      targetPort: 29092
  type: ClusterIP